# Generated by Django 5.2.4 on 2025-08-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_email_profile_shaba_number_profile_user_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('seller', 'Seller')], default='customer', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='store_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='store_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
