# Generated by Django 5.2.4 on 2025-08-09 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='verification_status',
        ),
    ]
