# Generated by Django 5.2.4 on 2025-08-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='en_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
